authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('profile/', authapp.profile, name='profile'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('update/', authapp.update, name='update'),
]

itbegin/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('profile/', authapp.profile, name='profile'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('update/', authapp.update, name='update'),
]

itbegin/itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import authapp
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('tasks/', mainapp.tasks, name='tasks'),
    path('task/<int:pk>', mainapp.task, name='task'),
    path('create_task/', mainapp.create_task, name='create_task'),
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class SiteUser(AbstractUser):
    avatar = models.ImageField(verbose_name="аватар пользователя", upload_to="user_avatars", blank=True)
    date_born = models.DateField(verbose_name="день рождения", null=True)
    profession = models.ManyToManyField(verbose_name="профессии", to='Professions', blank=True)
    about_me = models.CharField(verbose_name="обо мне", max_length=1000, blank=True)
    link_to_portfolio = models.CharField(max_length=150, blank=True)
    # my_groups = models.ManyToManyField(to='Groups', blank=True)
    # my_projects = models.ManyToManyField(to='Projects', blank=True)
    free = models.BooleanField(default=True)
    date_update_profile = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'


class ContactUser(models.Model):
    user = models.OneToOneField(SiteUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    user_phone = models.CharField(verbose_name="телефон", max_length=20, blank=True)
    user_email = models.EmailField(verbose_name="email", blank=True)
    user_instagram = models.URLField(verbose_name="инстаграмм", blank=True)
    user_vk = models.URLField(verbose_name="вконтакте", blank=True)
    user_telegram = models.URLField(verbose_name="телеграмм", blank=True)

    class Meta:
        verbose_name = 'контакты'
        verbose_name_plural = 'контакты'


class Professions(models.Model):
    profession_name = models.CharField(verbose_name="профессия", max_length=120)

    class Meta:
        verbose_name = 'профессии'
        verbose_name_plural = 'профессии'

    def __str__(self):
        return self.profession_name

itbegin/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class SiteUser(AbstractUser):
    avatar = models.ImageField(verbose_name="аватар пользователя", upload_to="user_avatars", blank=True)
    date_born = models.DateField(verbose_name="день рождения", null=True)
    profession = models.ManyToManyField(verbose_name="профессии", to='Professions', blank=True)
    about_me = models.CharField(verbose_name="обо мне", max_length=1000, blank=True)
    link_to_portfolio = models.CharField(max_length=150, blank=True)
    # my_groups = models.ManyToManyField(to='Groups', blank=True)
    # my_projects = models.ManyToManyField(to='Projects', blank=True)
    free = models.BooleanField(default=True)
    date_update_profile = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'


class ContactUser(models.Model):
    user = models.OneToOneField(SiteUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    user_phone = models.CharField(verbose_name="телефон", max_length=20, blank=True)
    user_email = models.EmailField(verbose_name="email", blank=True)
    user_instagram = models.URLField(verbose_name="инстаграмм", blank=True)
    user_vk = models.URLField(verbose_name="вконтакте", blank=True)
    user_telegram = models.URLField(verbose_name="телеграмм", blank=True)

    class Meta:
        verbose_name = 'контакты'
        verbose_name_plural = 'контакты'


class Professions(models.Model):
    profession_name = models.CharField(verbose_name="профессия", max_length=120)

    class Meta:
        verbose_name = 'профессии'
        verbose_name_plural = 'профессии'

    def __str__(self):
        return self.profession_name

authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms.widgets import HiddenInput, TextInput, PasswordInput

from authapp.models import SiteUser
from groupapp import forms


class SiteUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"


class SiteUserRegisterForm(UserCreationForm):
    class Meta:
        model = SiteUser
        fields = ('first_name', 'last_name', 'date_born', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"

    def save(self):
        user = super(SiteUserRegisterForm, self).save()

        user.is_active = True
        salt = hashlib.sha1(str(random.random()).encode('utf')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()
        return user


class SiteUserUpdateForm(UserChangeForm):
    class Meta:
        model = SiteUser
        fields = ('avatar', 'first_name', 'last_name', 'date_born', 'username',
                  'profession', 'about_me', 'link_to_portfolio')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"
            if field_name == 'password':
                field.widget = HiddenInput()

itbegin/authapp/forms.py
import hashlib
import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms.widgets import HiddenInput, TextInput, PasswordInput

from authapp.models import SiteUser
from groupapp import forms


class SiteUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"


class SiteUserRegisterForm(UserCreationForm):
    class Meta:
        model = SiteUser
        fields = ('first_name', 'last_name', 'date_born', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"

    def save(self):
        user = super(SiteUserRegisterForm, self).save()

        user.is_active = True
        salt = hashlib.sha1(str(random.random()).encode('utf')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()
        return user


class SiteUserUpdateForm(UserChangeForm):
    class Meta:
        model = SiteUser
        fields = ('avatar', 'first_name', 'last_name', 'date_born', 'username',
                  'profession', 'about_me', 'link_to_portfolio')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"
            if field_name == 'password':
                field.widget = HiddenInput()

authapp/views.py
from django.contrib import auth
from django.contrib.auth.models import User
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import UpdateView, FormView

from authapp.forms import SiteUserLoginForm, SiteUserRegisterForm, SiteUserUpdateForm
from authapp.models import Professions, SiteUser


def login(request):
    title = "вход"

    login_form = SiteUserLoginForm(data=request.POST or None)

    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("mainapp:index"))

    content = {"title": title, "forms": login_form}
    return render(request, "authapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("mainapp:index"))


def profile(request):
    title = 'личный кабинет'
    professions = SiteUser.objects.get(id=request.user.id).profession.all()
    content = {"title": title, 'professions': professions}

    return render(request, 'authapp/profile.html', context=content)


def register(request):
    title = "регистрация"

    if request.method == "POST":
        register_form = SiteUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        register_form = SiteUserRegisterForm()

    content = {
        "title": title,
        "forms": register_form
    }
    return render(request, "authapp/register.html", content)


def update(request):
    title = "изменения профиля"

    if request.method == "POST":
        form = SiteUserUpdateForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:profile'))
    else:
        form = SiteUserUpdateForm(instance=request.user)

    content = {
        "title": title,
        "forms": form
    }
    return render(request, "authapp/chang_profile.html", content)

itbegin/authapp/views.py
from django.contrib import auth
from django.contrib.auth.models import User
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import UpdateView, FormView

from authapp.forms import SiteUserLoginForm, SiteUserRegisterForm, SiteUserUpdateForm
from authapp.models import Professions, SiteUser


def login(request):
    title = "вход"

    login_form = SiteUserLoginForm(data=request.POST or None)

    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("mainapp:index"))

    content = {"title": title, "forms": login_form}
    return render(request, "authapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("mainapp:index"))


def profile(request):
    title = 'личный кабинет'
    professions = SiteUser.objects.get(id=request.user.id).profession.all()
    content = {"title": title, 'professions': professions}

    return render(request, 'authapp/profile.html', context=content)


def register(request):
    title = "регистрация"

    if request.method == "POST":
        register_form = SiteUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        register_form = SiteUserRegisterForm()

    content = {
        "title": title,
        "forms": register_form
    }
    return render(request, "authapp/register.html", content)


def update(request):
    title = "изменения профиля"

    if request.method == "POST":
        form = SiteUserUpdateForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:profile'))
    else:
        form = SiteUserUpdateForm(instance=request.user)

    content = {
        "title": title,
        "forms": form
    }
    return render(request, "authapp/chang_profile.html", content)

itbegin/authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>

    </style>
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/pages/index.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/pages/account.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/pages/authorization.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/pages/registration.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/pages/team.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/pages/teams.css' %}"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link
                href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,500;0,700;1,600&family=Rubik:wght@400;500&family=Vollkorn:wght@600&display=swap"
                rel="stylesheet"
        />
    {% endblock %}

    {% block js %}
         <script src="{% static 'js/script.js' %}"></script>
    {% endblock js %}

</head>

{#<body class="root registration__form__background">#}
<body>

{% block content %}
{% endblock content %}


</body>
</html>

itbegin/authapp/templates/authapp/chang_profile.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="registration__form__background">
        <section class="registration__form__content root__container">
            <a href="{% url 'authapp:profile' %}" class="button__registration__form">
                <img class="button__registration__form__img" src="/static/img/Arrow.png">
                Назад
            </a>
            <h1 class="registration__form__content__h1">
                Заполни форму
            </h1>
            <form action="{% url 'authapp:update' %}" class="registration__form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for form in forms %}
                    {% if form.label != 'Пароль' %}
                    <div>
                        <label for="{{ form.id_for_label }}"
                               class="registration__form_input_label"> {{ form.label }} </label>
                        {{ form }}
                    </div>
                    {% endif %}
                {% endfor %}
                <input type="submit" value="Сохранить"
                       class="buttons_type_white button__submit__registration__form" id="submit__application">
            </form>
        </section>
    </div>

{% endblock content %}

itbegin/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="root darkgrey_background authorization__page">
        <section class="authorization__block">
            <a href="{% url 'authapp:login' %}">Вход</a>
            <a href="{% url 'authapp:register' %}">Регистрация</a>
        </section>
        <section class="authorization__main root__container">
            <form action="{% url 'authapp:login' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for form in forms %}
                    <div>
                        <label for="{{ form.id_for_label }}"
                               class="registration__form_input_label"> {{ form.label }} </label>
                        {{ form }}
                    </div>
                {% endfor %}
                </br>
                <label class="registration__form_checkbox"><input type="checkbox" required name="personalinfo"
                                                                  id="personalinfo">
                    <span class="registration__form_checkmark"></span>
                    Запомнить меня</label>
                <input type="submit" value="Войти"
                       class="buttons_type_white button__submit__registration__form" id="submit__application">
            </form>
            <a href="#" class="authorization__password__link">Забыли пароль?</a>
        </section>
    </div>


{% endblock content %}

itbegin/authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}



    <section class="account root__container">
        <div class="account__background">
            <div class="account__header root__content">
                <p>Профиль</p>
                <div class="account__header__left">
                    <a href="#" class="account__link"><i class="fas fa-cog"></i></a>
                    <a href="#" class="account__link"><i class="far fa-envelope"></i><sup>2</sup></a>
                    <div class="drop_block account__drop"> Возможности<i class="fas fa-caret-down drop_caret"></i>
                        <div class="drop_summary account__summary">
                            <a href="#">Найти задачу</a>
                            <a href="#">Найти проект</a>
                            <a href="#">Создать проект</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="account__profile root__content">
                <div class="account__profile__info">
                    <div class="account__avatar">
                        {#                        <img src="/static/{% if user.avatar %}{{ user.avatar }}{% else %}img/avatar.png{% endif %}"#}
                        {#                             alt="avatar">#}
                        <img src=" {{ user.avatar }}"
                             alt="avatar">
                        <a href="#"><i class="fas fa-pen"></i> Изменить</a>
                    </div>
                    <div class="account__info">
                        <p class="account__headline">{{ user.first_name }} {{ user.last_name }}</p>
                        <p>Выполнено заданий 0 &#183; Работ в портфолио 5</p>
                        <p>Статус: свободен</p>
                    </div>
                </div>
                <a href="#">{{ user.about_me }}</a>
            </div>
            <div class="account__content root__content">
                <div class="account__content__div">
                    <p class="account__headline">Специализации</p>
                    {% for profession in professions %}
                        <p class="account__headline">{{ profession }}</p>
                    {% endfor %}
                </div>
                <div class="account__content__div">
                    <p class="account__headline">Работы</p>
                    <p>Landing page &#183; Интернет-магазин</p>
                </div>
            </div>
            <div class="root__content">
                <div class="account__information">
                    <p class="account__headline">Контакты</p>
                    <p class="account__links">
                        <a href="#"><img src="/static/img/instagram-logo.png" alt="instagram"></a>
                        <a href="#"><img src="/static/img/vkontakte-logo.png" alt="vkontakte"></a>
                        <a href="#"><img src="/static/img/telegram-logo.png" alt="telrgram"></a>
                    </p>
                </div>
                <div class="account__information">
                    <a href="#">
                        <p class="account__headline">Мои статьи</p>
                    </a>
                    <a href="#" class="account__link account__links"><i class="far fa-heart"></i></a>
                </div>
                <div class="account__information">
                    <a href="#">
                        <p class="account__headline">Форум</p>
                    </a>
                    <a href="#" class="account__link account__links"><i class="far fa-heart"></i></a>
                </div>
            </div>
            <div class="account__buttons root__content">
                <a href="team.html">
                    <button class="account__button buttons_type_white">Мои команды</button>
                </a>
                <button class="account__button buttons_type_white">Мои проекты</button>
                <button class="account__button buttons_type_white"><a href="{% url 'authapp:update' %}"> Редактировать
                    профиль</a></button>
                <button class="account__exit__btn buttons_type_white"><a href="{% url 'authapp:logout' %}">Выход</a>
                </button>
            </div>
        </div>
    </section>

{% endblock %}

itbegin/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="registration__form__background">
        <section class="registration__form__content root__container">
            <a href="{% url 'mainapp:index' %}" class="button__registration__form">
                <img class="button__registration__form__img" src="/static/img/Arrow.png">
                Назад
            </a>
            <h1 class="registration__form__content__h1">
                Заполни форму, что бы зарегистрироваться
            </h1>
            <form action="{% url 'authapp:register' %}" class="registration__form" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% for form in forms %}
                    <div>
                        <label for="{{ form.id_for_label }}"
                               class="registration__form_input_label"> {{ form.label }} </label>
                        {{ form }}
                    </div>
                {% endfor %}

                <label class="registration__form_checkbox">
                    <input type="checkbox" required name="personalinfo" id="personalinfo">
                    <span class="registration__form_checkmark"></span>
                    Согласие на использование персональной информации
                </label>
                <input type="submit" value="Зарегистрироваться"
                       class="buttons_type_white button__submit__registration__form" id="submit__application">
            </form>
        </section>

    </div>
{% endblock content %}