authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('profile/', authapp.profile, name='profile'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('update/', authapp.update, name='update'),
]

groupapp/urls.py
from django.urls import path

from django.urls import path

import groupapp.views as groupapp

app_name = 'groupapp'

urlpatterns = [
    path('groups/', groupapp.groups, name='groups'),
    # path('create_group/', groupapp.create_group, name='create_group'),
    path('create_group/', groupapp.GroupCreateView.as_view(), name='create_group'),
    path('group/<int:pk>', groupapp.group, name='group'),
    path('update_group/<int:pk>/', groupapp.GroupUpdateView.as_view(), name='update_group'),
    path('delete_group/<int:pk>/', groupapp.GroupDeleteView.as_view(), name='delete_group'),
    path('create_request_in_team/', groupapp.create_request_in_team, name='create_request_in_team'),
    path('setting/<int:pk>/', groupapp.SettingView.as_view(), name='setting_group'),
    path('update_vacancy/<int:pk>/', groupapp.VacancyUpdate.as_view(), name='update_vacancy'),
    path('user_groups/', groupapp.UserGroupView.as_view(), name='user_groups'),
]

itbegin/itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import authapp
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('tasks/', mainapp.tasks, name='tasks'),
    path('task/<int:pk>', mainapp.task, name='task'),
    path('create_task/', mainapp.create_task, name='create_task'),
]

itbegin/mainapp/models.py
from django.db import models

from authapp.models import SiteUser, Professions


class Task(models.Model):
    name = models.CharField(verbose_name='название', max_length=150)
    short_description = models.CharField(verbose_name='краткое описанние', max_length=1000)
    full_description = models.TextField(verbose_name='полное описание')
    tz = models.TextField(verbose_name='техническое задание')
    author = models.ForeignKey(to=SiteUser, on_delete=models.CASCADE)
    # developers = models.ManyToManyField(to=Groups)
    professions = models.ManyToManyField(to=Professions)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    quantity_take = models.IntegerField(verbose_name='количество взятий', default=0)
    quantity_finished = models.IntegerField(verbose_name='количество выполнения', default=0)
    # reviews = models.ManyToManyField()
    rating = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = 'задача'
        verbose_name_plural = 'задачи'

    def __str__(self):
        return self.name

mainapp/models.py
from django.db import models

from authapp.models import SiteUser, Professions


class Task(models.Model):
    name = models.CharField(verbose_name='название', max_length=150)
    short_description = models.CharField(verbose_name='краткое описанние', max_length=1000)
    full_description = models.TextField(verbose_name='полное описание')
    tz = models.TextField(verbose_name='техническое задание')
    author = models.ForeignKey(to=SiteUser, on_delete=models.CASCADE)
    # developers = models.ManyToManyField(to=Groups)
    professions = models.ManyToManyField(to=Professions)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    quantity_take = models.IntegerField(verbose_name='количество взятий', default=0)
    quantity_finished = models.IntegerField(verbose_name='количество выполнения', default=0)
    # reviews = models.ManyToManyField()
    rating = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name = 'задача'
        verbose_name_plural = 'задачи'

    def __str__(self):
        return self.name

itbegin/mainapp/forms.py
from django import forms
from django.forms import ModelForm
from django.template.context_processors import request

from mainapp.models import Task


class CreateTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'short_description', 'full_description', 'tz', 'professions')

    def __init__(self, *args, **kwargs):
        super(CreateTaskForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

mainapp/forms.py
from django import forms
from django.forms import ModelForm
from django.template.context_processors import request

from mainapp.models import Task


class CreateTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'short_description', 'full_description', 'tz', 'professions')

    def __init__(self, *args, **kwargs):
        super(CreateTaskForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

itbegin/mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from mainapp.forms import CreateTaskForm
from mainapp.models import Task


def index(request):
    title = 'главная'
    content = {"title": title}
    return render(request, 'mainapp/index.html', context=content)


def tasks(request):
    title = 'задачи'
    tasks = Task.objects.all()

    content = {'title': title, 'tasks': tasks}
    return render(request, 'mainapp/tasks.html', context=content)


def task(request, pk):
    title = 'задача'
    task_obj = Task.objects.get(pk=pk)

    content = {'title': title, 'task': task_obj}
    return render(request, 'mainapp/task.html', context=content)


def create_task(request):
    title = 'создание задачи'

    if request.method == "POST":
        create_task_form = CreateTaskForm(request.POST, request.FILES)
        if create_task_form.is_valid():
            new_task = create_task_form.save(commit=False)
            new_task.author = request.user
            new_task.save()

            return HttpResponseRedirect(reverse('mainapp:tasks'))

    else:
        create_task_form = CreateTaskForm()

    content = {'title': title, 'create_task_form': create_task_form}

    return render(request, "mainapp/create_task.html", context=content)

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from mainapp.forms import CreateTaskForm
from mainapp.models import Task


def index(request):
    title = 'главная'
    content = {"title": title}
    return render(request, 'mainapp/index.html', context=content)


def tasks(request):
    title = 'задачи'
    tasks = Task.objects.all()

    content = {'title': title, 'tasks': tasks}
    return render(request, 'mainapp/tasks.html', context=content)


def task(request, pk):
    title = 'задача'
    task_obj = Task.objects.get(pk=pk)

    content = {'title': title, 'task': task_obj}
    return render(request, 'mainapp/task.html', context=content)


def create_task(request):
    title = 'создание задачи'

    if request.method == "POST":
        create_task_form = CreateTaskForm(request.POST, request.FILES)
        if create_task_form.is_valid():
            new_task = create_task_form.save(commit=False)
            new_task.author = request.user
            new_task.save()

            return HttpResponseRedirect(reverse('mainapp:tasks'))

    else:
        create_task_form = CreateTaskForm()

    content = {'title': title, 'create_task_form': create_task_form}

    return render(request, "mainapp/create_task.html", context=content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title|default:"IT-Begin" }}</title>

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/pages/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/account.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/authorization.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/registration.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/task.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/tasks.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/team.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pages/teams.css' %}" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
        href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,500;0,700;1,600&family=Rubik:wght@400;500&family=Vollkorn:wght@600&display=swap"
        rel="stylesheet" />

    {% endblock %}


    {% block js %}
    <script src="https://kit.fontawesome.com/4c151273f1.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}" defer></script>
    {% endblock %}

</head>

<body class="root">
    <section class="header root__container">
        {% include 'mainapp/includes/inc__main_menu.html' %}

    </section>
    {% block conteiner %}

    {% endblock %}
    <section class="footer root__container">
        <div class="footer__content root__content">
            <a href={% url 'mainapp:index' %}>
                <img class="footer__logo" src="{% static '/img/logo-black.png' %}" alt="Лого" />
            </a>
            <div class="footer__about">
                <a href="#" class="footer__link">О проекте</a>
                <a href="#" class="footer__link">Контакты</a>
            </div>
            <div class="footer__questions">
                <a href="#" class="footer__link">Пользовательское соглашение</a>
                <a href="#" class="footer__link">Задать вопрос</a>
            </div>
            <div class="footer__subscribe">
                <p class="footer__subscribe-title">Подписаться на новости</p>
                <input name="email" placeholder="E-mail" type="e-mail"
                    class="input_type_white footer__subscribe-input" />
                <button class="buttons_type_darkGray footer__button">
                    Подписаться
                </button>
            </div>
        </div>
    </section>
</body>

</html>

mainapp/templates/mainapp/create_task.html
{% extends 'authapp/base.html' %}
{% block content %}

    <form class="form-horizontal" action="{% url 'mainapp:create_task' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ create_task_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="создать">
    </form>
    <a href="{% url 'mainapp:tasks' %}" class="btn btn-outline-secondary btn-block" role="button">
        назад
    </a>
{{ request.user.pk }}


{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}

<section class="main root__container">
  <div class="main__background">
    <div class="main__content root__content">
      <h1 class="main__title">Получи опыт в своей новой IT профессии</h1>
      <h2 class="main__subtitle">
        Находи задачи и создавай команды для реализации своих идей!
      </h2>
      <div class="main__buttons">
        <a href="{% url 'mainapp:tasks' %}" class="buttons_type_white main__button">
          Найти задачу
        </a>
        <a href="{% url 'groupapp:create_group' %}" class="buttons_type_white main__button">
          Создать команду
        </a>
      </div>
    </div>
  </div>
</section>
<section class="news root__container">
  <div class="news__content root__content">
    <div class="news__articles">
      <div class="news__header">
        <p class="news__header-label">Новости</p>
        <select class="selects_type_darkGray news__select">
          <option value="all">Все категории</option>
          <option value="kat1">Категория 1</option>
          <option value="kat2">Категория 2</option>
          <option value="kat3">Категория 3</option>
        </select>
      </div>
      <div class="news__article">
        <img src="/static/img/news1.png" class="news__article-img" />
        <div class="article">
          <h2 class="article__label">Тема</h2>
          <p class="article__text">Описание Новости</p>
          <p class="article__data">Дата</p>
        </div>
      </div>
      <div class="news__article">
        <img src="/static/img/news1.png" class="news__article-img" />
        <div class="article">
          <h2 class="article__label">Тема</h2>
          <p class="article__text">Описание Новости</p>
          <p class="article__data">Дата</p>
        </div>
      </div>
      <div class="news__article">
        <img src="/static/img/news1.png" class="news__article-img" />
        <div class="article">
          <h2 class="article__label">Тема</h2>
          <p class="article__text">Описание Новости</p>
          <p class="article__data">Дата</p>
        </div>
      </div>
      <div class="news__footer">
        <button class="buttons_type_darkGray news__load">
          Загрузить еще
        </button>
      </div>
    </div>
    <div class="news__forum">
      <img src="/static/img/forum.jpg" alt="Форум" />
    </div>
  </div>
</section>

{% endblock %}

mainapp/templates/mainapp/task.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}
<section class="task root__container">
    <div class="task__background">
        <div class="task__header root__content">
            <p>Задача</p>
        </div>
        <div class="task__description root__content">
            <p class="task__description__p">Название задачи</p>
            <p class="task__description__p">Описание задачи</p>
        </div>

    </div>
</section>
Task
<ul>
    {{ task }}
    <li>----------------------------------------------------------------</li>
    <li> {{ task.name }}</li>
    <li> {{ task.short_description }}</li>
    <li>{{ task.full_description }}</li>
    <li>{{ task.tz }}</li>
    <li>{{ task.author }}</li>
    <li>{{ task.id }}</li>

    <li>----------------------------------------------------------------</li>

</ul>
<a href="{% url 'mainapp:tasks' %}">задачи</a>
{% endblock %}

mainapp/templates/mainapp/tasks.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}
<section class="tasks root__container">
    <div class="tasks__background">
        <div class="tasks__header root__content">
            <p>Задачи</p>
            <div class="teams__drop">
                <div class="drop_block"> Категории<i class="fas fa-caret-down drop_caret"></i>
                    <div class="drop_summary teams__summary">
                        <a href="#"></a>
                        <a href="#"></a>
                        <a href="#"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="tasks__content root__content">
            <p class="team__headline">Название</p>
            <p class="tasks__description">Описание</p>
        </div>
        <div class="root__content">
            <!-- <p style="color: white;">Tasks</p> -->
            <ul style="color: white;">
                {% for task in tasks %}
                <li>----------------------------------------------------------------</li>
                <li> {{ task.name }}</li>
                <li> {{ task.short_description }}</li>
                <li>{{ task.full_description }}</li>
                <li>{{ task.tz }}</li>
                <li>{{ task.author }}</li>
                <li>{{ task.id }}</li>
                <li><a href="{% url 'mainapp:task' task.id %}">Task</a> </li>
                <li>----------------------------------------------------------------</li>
                {% endfor %}
            </ul>
            <a href="{% url 'mainapp:create_task' %}" style="color: white;">Создать задачу</a>
        </div>
    </div>

</section>

{% endblock %}