authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('profile/', authapp.profile, name='profile'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('update/', authapp.update, name='update'),
]

itbegin/itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messegeapp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

import messegeapp.views as messegeapp


app_name = 'messegeapp'

urlpatterns = [
 url(r'^dialogs/$', login_required(messegeapp.DialogView.as_view()), name='dialogs'),
 url(r'^dialogs/create/(?P<user_id>\d+)/$', login_required(messegeapp.CreateDialogView.as_view()), name='create_dialog'),
 url(r'^dialogs/(?P<chat_id>\d+)/$', login_required(messegeapp.MessageView.as_view()), name='messages'),
 ]

itbegin/messegeapp/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from authapp.models import SiteUser


class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, 'Dialog'),
        (CHAT, 'Chat')
    )

    type = models.CharField(verbose_name='Тип', max_length=1, choices=CHAT_TYPE_CHOICES, default=DIALOG)
    members = models.ManyToManyField(SiteUser, verbose_name='участник')

    def get_absolute_url(self):
        return reverse('messegeapp:messages', (), {'chat_id': self.pk})


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name='чат', on_delete=models.CASCADE)
    author = models.ForeignKey(SiteUser, verbose_name='пользователь', on_delete=models.CASCADE)
    massage = models.TextField(verbose_name='сообщения')
    pub_date = models.DateTimeField(verbose_name='дата сообщения', auto_now_add=True)
    is_read = models.BooleanField(verbose_name='прочитано', default=False)
    is_active = models.BooleanField(verbose_name='удалено', default=True)

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.massage

messegeapp/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from authapp.models import SiteUser


class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, 'Dialog'),
        (CHAT, 'Chat')
    )

    type = models.CharField(verbose_name='Тип', max_length=1, choices=CHAT_TYPE_CHOICES, default=DIALOG)
    members = models.ManyToManyField(SiteUser, verbose_name='участник')

    def get_absolute_url(self):
        return reverse('messegeapp:messages', (), {'chat_id': self.pk})


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name='чат', on_delete=models.CASCADE)
    author = models.ForeignKey(SiteUser, verbose_name='пользователь', on_delete=models.CASCADE)
    massage = models.TextField(verbose_name='сообщения')
    pub_date = models.DateTimeField(verbose_name='дата сообщения', auto_now_add=True)
    is_read = models.BooleanField(verbose_name='прочитано', default=False)
    is_active = models.BooleanField(verbose_name='удалено', default=True)

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.massage

itbegin/messegeapp/forms.py
from django.forms.models import ModelForm
from messegeapp.models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['massage']
        labels = {'massage': ""}

messegeapp/forms.py
from django.forms.models import ModelForm
from messegeapp.models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['massage']
        labels = {'massage': ""}

itbegin/messegeapp/views.py
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import View

from messegeapp.forms import MessageForm
from messegeapp.models import Chat


class DialogView(View):

    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        return render(request, 'messageapp/dialog.html', {'user_profiler': request.user, 'chats': chats})


class MessageView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_read=False).exclude(author=request.user).update(is_read=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None
        content = {
            'user_profile': request.user,
            'chat': chat,
            'form': MessageForm()
        }
        return render(request, 'messageapp/messages.html', context=content)

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('messegeapp:messages', kwargs={'chat_id': chat_id}))


class CreateDialogView(View):
    def get(self, request, user_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id], type=Chat.DIALOG).annotate(
            c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('messegeapp:messages', kwargs={'chat_id': chat.id}))

messegeapp/views.py
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import View

from messegeapp.forms import MessageForm
from messegeapp.models import Chat



class DialogView(View):

    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        return render(request, 'messageapp/dialog.html', {'user_profiler': request.user, 'chats': chats})


class MessageView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_read=False).exclude(author=request.user).update(is_read=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None
        content = {
            'user_profile': request.user,
            'chat': chat,
            'form': MessageForm()
        }
        return render(request, 'messageapp/messages.html', context=content)

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('messegeapp:messages', kwargs={'chat_id': chat_id}))


class CreateDialogView(View):
    def get(self, request, user_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id], type=Chat.DIALOG).annotate(
            c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('messegeapp:messages', kwargs={'chat_id': chat.id}))

itbegin/messegeapp/templates/messageapp/dialog.html
{% load i18n %}
{% load companion %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="panel">
    {% load tz %}
    {% if chats.count == 0 %}
        <div class="panel panel-body">{% trans "Нет ни одного начатого диалога" %}</div>
    {% endif %}
    {% for chat in chats %}
        {% if chat.message_set.count != 0 %}
            {% with last_message=chat.message_set.last %}
                {% get_companion user chat as companion %}
                <a class="list-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %}"
                   href="{{ chat.get_absolute_url }}">
                    <img class="avatar-messages" src="{{ companion.userprofile.get_avatar }}">
                    <div class="reply-body">
                        <ul class="list-inline">
                            <li class="drop-left-padding">
                                <strong class="list-group-item-heading">{{ companion.username }}</strong>
                            </li>
                            <li class="pull-right text-muted"><small>{{ last_message.pub_date|utc }}</small></li>
                        </ul>
                        {% if companion != last_message.author %}
                            <div>
                                <img class="avatar-rounded-sm" src="{{ last_message.author.userprofile.get_avatar }}">
                                <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            </div>
                        {% else %}
                            <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                        {% endif %}
                    </div>
                </a>
            {% endwith %}
        {% endif %}
    {% endfor %}
</div>
</body>
</html>

itbegin/messegeapp/templates/messageapp/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% url 'authapp:profile' message_item.author.username as the_user_url%}
{% load tz %}
<div class="list-group-item {% if not message_item.is_readed %}unreaded{% endif %}">
    <a href="{{ the_user_url }}"><img class="avatar-comment" src="{{ message_item.author.userprofile.get_avatar }}"></a>
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong class="list-group-item-heading"><a href="{{ the_user_url }}">{{ message_item.author.username }}</a></strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message_item.pub_date|utc }}</small></li>
        </ul>
        <div>{{ message_item.message|safe }}</div>
    </div>
</div>
</body>
</html>

itbegin/messegeapp/templates/messageapp/messages.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if not chat %}
    <div class="panel panel-body">
        {% trans "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе." %}
    </div>
{% else %}
    {% load tz %}
    {% if chat %}
        <div id="messages" class="panel">
            <div id="innerMessages">
                {% for message in chat.message_set.all %}
                        {% include 'messageapp/message.html' with message_item=message %}
                    {{ message }}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div id="message_form">
        <form id="message-form" class="panel panel-body" method="post" >

            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-default btn-sm" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>{% trans "Отправить" %}</button>
        </form>
    </div>
{% endif %}
</body>
</html>