authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('profile/', authapp.profile, name='profile'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('update/', authapp.update, name='update'),
]

groupapp/urls.py
from django.urls import path

from django.urls import path

import groupapp.views as groupapp

app_name = 'groupapp'

urlpatterns = [
    path('groups/', groupapp.groups, name='groups'),
    # path('create_group/', groupapp.create_group, name='create_group'),
    path('create_group/', groupapp.GroupCreateView.as_view(), name='create_group'),
    path('group/<int:pk>', groupapp.group, name='group'),
    path('update_group/<int:pk>/', groupapp.GroupUpdateView.as_view(), name='update_group'),
    path('delete_group/<int:pk>/', groupapp.GroupDeleteView.as_view(), name='delete_group'),
    path('create_request_in_team/', groupapp.create_request_in_team, name='create_request_in_team'),
    path('setting/<int:pk>/', groupapp.SettingView.as_view(), name='setting_group'),
    path('update_vacancy/<int:pk>/', groupapp.VacancyUpdate.as_view(), name='update_vacancy'),
    path('user_groups/', groupapp.UserGroupView.as_view(), name='user_groups'),
]

itbegin/itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itbegin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls'), name='mainapp'),
    path('auth/', include('authapp.urls'), name='authapp'),
    path('group/', include('groupapp.urls'), name='groupapp'),
    path('message/', include('messegeapp.urls'), name='messegeapp'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupapp/models.py
from django.db import models
from django.urls import reverse

from authapp.models import SiteUser, Professions
from mainapp.models import Task


class Group(models.Model):
    name = models.CharField(max_length=120)
    # При удаление бд убрать null=True
    author = models.ForeignKey(to=SiteUser,related_name='author_group', on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=200, blank=True)
    need_profession = models.ManyToManyField(to=Professions, through='DescriptionNeedProfessions')
    team_members = models.ManyToManyField(to=SiteUser, null=True)
    logotype = models.ImageField(blank=True)
    got_task = models.ManyToManyField(to=Task, related_name='got_task', null=True)
    done_task = models.ManyToManyField(to=Task, related_name='done_task', blank=True)
    # groups_chat = models.URLField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('groupapp:group', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'команда'
        verbose_name_plural = 'команды'


class DescriptionNeedProfessions(models.Model):
    profession = models.ForeignKey(Professions, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    description = models.TextField(blank=True)

itbegin/groupapp/models.py
from django.db import models

from authapp.models import SiteUser, Professions
from mainapp.models import Task


class Group(models.Model):
    name = models.CharField(max_length=120)
    # При удаление бд убрать null=True
    author = models.ForeignKey(to=SiteUser,related_name='author_group', on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=200, blank=True)
    need_profession = models.ManyToManyField(to=Professions, through='DescriptionNeedProfessions')
    team_members = models.ManyToManyField(to=SiteUser, null=True)
    logotype = models.ImageField(blank=True)
    got_task = models.ManyToManyField(to=Task, related_name='got_task', null=True)
    done_task = models.ManyToManyField(to=Task, related_name='done_task', blank=True)
    # groups_chat = models.URLField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'команда'
        verbose_name_plural = 'команды'


class DescriptionNeedProfessions(models.Model):
    profession = models.ForeignKey(Professions, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    description = models.TextField(blank=True)

groupapp/forms.py
from django.forms.models import ModelForm
from django.forms.widgets import HiddenInput

from groupapp.models import Group, Professions, DescriptionNeedProfessions


class CreateGroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'description', 'need_profession', 'logotype')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"


class UpdateVacancyForm(ModelForm):
    class Meta:
        model = DescriptionNeedProfessions
        fields = ['id', 'group', 'profession', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"

itbegin/groupapp/forms.py
from django.forms.models import ModelForm
from django.forms.widgets import HiddenInput

from groupapp.models import Group, Professions, DescriptionNeedProfessions


class CreateGroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'description', 'need_profession', 'logotype')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"


class UpdateVacancyForm(ModelForm):
    class Meta:
        model = DescriptionNeedProfessions
        fields = ['id', 'group', 'profession', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "input_type_black registration__form_input"

groupapp/views.py
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from authapp.models import SiteUser
from groupapp.forms import CreateGroupForm, UpdateVacancyForm
from groupapp.models import Group, DescriptionNeedProfessions


def groups(request):
    title = 'команды'
    groups = Group.objects.filter(is_active=True)

    content = {'title': title, 'object_list': groups}
    return render(request, 'groupapp/groups.html', context=content)


class UserGroupView(ListView):
    model = Group
    template_name = 'groupapp/groups.html'

    def get_queryset(self):
        return Group.objects.filter(author=self.request.user)


# def create_group(request):
#     title = "создание команды"
#
#     if request.method == "POST":
#         create_group_form = CreateGroupForm(request.POST, request.FILES)
#
#         if create_group_form.is_valid():
#             new_group = create_group_form.save(commit=False)
#             new_group.author = request.user
#             new_group.save()
#             new_group.need_profession.add(*create_group_form.data.getlist('need_profession'))
#             return HttpResponseRedirect(reverse('groupapp:groups'))
#     else:
#         create_group_form = CreateGroupForm()
#
#     content = {
#         "title": title,
#         "object_list": create_group_form
#     }
#     return render(request, "groupapp/create_group.html", content)

class GroupCreateView(CreateView):
    model = Group
    form_class = CreateGroupForm
    template_name = 'groupapp/create_group.html'
    # success_url = reverse_lazy('groupapp:groups')

    def post(self, request, *args, **kwargs):
        '''
        added to the method author=user
        '''
        form = self.get_form()
        if form.is_valid():
            new_group = form.save(commit=False)
            new_group.author = request.user
            new_group.save()
            new_group.need_profession.add(*form.data.getlist('need_profession'))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def group(request, pk):
    title = 'команда'
    this_group = Group.objects.get(pk=pk)
    need_professions = this_group.need_profession.all()
    team_professions = SiteUser.objects.get(id=request.user.id).profession.all()
    members = SiteUser.objects.filter(group__team_members__group=pk)

    content = {
        'title': title,
        'this_group': this_group,
        'need_professions': need_professions,
        'team_professions': team_professions,
        'members': members
    }
    return render(request, 'groupapp/group.html', context=content)


class GroupUpdateView(UpdateView):
    model = Group
    form_class = CreateGroupForm
    template_name = 'groupapp/create_group.html'
    success_url = reverse_lazy('groupapp:groups')


class GroupDeleteView(DeleteView):
    model = Group
    success_url = reverse_lazy('groupapp:groups')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)


class SettingView(ListView):
    """
    page setting group
    """
    model = Group


class VacancyUpdate(UpdateView):
    """
    form description vacancy of group
    """
    model = Group
    fields = []
    success_url = reverse_lazy('groupapp:groups')

    def get_context_data(self, **kwargs):
        data = super(VacancyUpdate, self).get_context_data(**kwargs)
        VacancyFormSet = inlineformset_factory(Group, DescriptionNeedProfessions, form=UpdateVacancyForm, extra=1)
        pk = self.kwargs.get('pk')

        if self.request.POST:
            formset = VacancyFormSet(self.request.POST, instance=Group.objects.get(id=pk))
        else:
            need_profession = DescriptionNeedProfessions.objects.filter(group=pk)
            if len(need_profession):
                VacancyFormSet = inlineformset_factory(Group, DescriptionNeedProfessions, form=UpdateVacancyForm,
                                                       extra=len(need_profession))
                formset = VacancyFormSet()
                for el, form in enumerate(formset.forms):
                    form.initial['profession'] = need_profession[el].profession
                    form.initial['description'] = need_profession[el].description
                    form.initial['group'] = need_profession[el].group
                    form.initial['id'] = need_profession[el].id
        data['vacancyneed'] = formset
        return data

    def form_valid(self, form):
        """need refactor"""
        if form.is_valid:
            my_list = []
            a = []
            for key, el in form.data.items():
                if key[33:] == 'description':
                    a.append(el)
                if key[33:] == 'id':
                    a.append(el)
                    my_list.append(a)
                    a = []
            for el in my_list:
                idx = int(el[1])
                dis = el[0]
                f = DescriptionNeedProfessions.objects.get(id=idx)
                f.description = dis
                f.save()
            form.save()
            return super().form_valid(form)


def create_request_in_team(request):
    pass

itbegin/groupapp/views.py
from django.forms import formset_factory, inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView

from authapp.models import Professions, SiteUser
from groupapp.forms import CreateGroupForm, UpdateVacancyForm
from groupapp.models import Group, DescriptionNeedProfessions


def groups(request):
    title = 'команды'
    groups = Group.objects.filter(is_active=True)

    content = {'title': title, 'groups': groups}
    return render(request, 'groupapp/groups.html', context=content)


def group(request, pk):
    title = 'команда'
    this_group = Group.objects.get(pk=pk)
    need_professions = this_group.need_profession.all()
    team_professions = SiteUser.objects.get(id=request.user.id).profession.all()
    members = SiteUser.objects.filter(group__team_members__group=pk)

    content = {
        'title': title,
        'this_group': this_group,
        'need_professions': need_professions,
        'team_professions': team_professions,
        'members': members
    }
    return render(request, 'groupapp/group.html', context=content)


def create_group(request):
    title = "создание команды"

    if request.method == "POST":
        create_group_form = CreateGroupForm(request.POST, request.FILES)

        if create_group_form.is_valid():
            new_group = create_group_form.save(commit=False)
            new_group.author = request.user
            new_group.save()
            new_group.need_profession.add(*create_group_form.data.getlist('need_profession'))
            return HttpResponseRedirect(reverse('groupapp:groups'))
    else:
        create_group_form = CreateGroupForm()

    content = {
        "title": title,
        "forms": create_group_form
    }
    return render(request, "groupapp/create_group.html", content)


class SettingView(ListView):
    model = Group


class VacancyUpdate(UpdateView):
    model = Group
    fields = []
    success_url = reverse_lazy('groupapp:groups')

    def get_context_data(self, **kwargs):
        data = super(VacancyUpdate, self).get_context_data(**kwargs)
        VacancyFormSet = inlineformset_factory(Group, DescriptionNeedProfessions, form=UpdateVacancyForm, extra=1)
        pk = self.kwargs.get('pk')

        if self.request.POST:
            formset = VacancyFormSet(self.request.POST)
        else:
            need_profession = DescriptionNeedProfessions.objects.filter(group=pk)
            if len(need_profession):
                VacancyFormSet = inlineformset_factory(Group, DescriptionNeedProfessions, form=UpdateVacancyForm,
                                                       extra=len(need_profession))
                formset = VacancyFormSet()
                for el, form in enumerate(formset.forms):
                    form.initial['profession'] = need_profession[el].profession
                    form.initial['description'] = need_profession[el].description
                    form.initial['group'] = need_profession[el].group
                    form.initial['id'] = need_profession[el].id
            else:
                formset = VacancyFormSet()
        data['vacancyneed'] = formset
        return data

    # def form_valid(self, form):
    #     context = self.get_context_data()
    #     vacancyneed = context['vacancyneed']
    #     self.object = form.save()
    #     if vacancyneed.is_valid():
    #         vacancyneed.instance = self.object
    #         vacancyneed.save()

        # return super(VacancyUpdate, self).form_valid(form)


def create_request_in_team(request):
    pass

groupapp/templates/groupapp/create_group.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block conteiner %}
    <div class="registration__form__background">
        <section class="registration__form__content root__container">
            <a href="{% url 'groupapp:groups' %}" class="button__registration__form">
                <img class="button__registration__form__img" src="/static/img/Arrow.png">
                Назад
            </a>
            <h1 class="registration__form__content__h1">
                Заполни форму, что бы создать команду
            </h1>
            <form class="registration__form" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div>
                        <label for="{{ field.id_for_label }}"
                               class="registration__form_input_label"> {{ field.label }} </label>
                        {{ field }}
                    </div>
                {% endfor %}


                <input type="submit" value="Создать"
                       class="buttons_type_white button__submit__registration__form" id="submit__application">
            </form>
        </section>

    </div>
{% endblock %}

groupapp/templates/groupapp/group.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}

    <section class="team root__container">
        <div class="account__background">
            <div class="account__header root__content">
                <p>Команда</p>
                <div class="team__header__task">
                    {% if this_group.author == user %}
                        <div class="team__header__task">
                        <a href="{% url 'groupapp:setting_group' request.resolver_match.kwargs.pk %}">настройки</a>
                        </div>
                    {% endif %}
                    <div class="drop_block team__drop"> Задачи<i class="fas fa-caret-down drop_caret"></i>
                        <div class="drop_summary account__summary">
                            <a href="#">Взятые</a>
                            <a href="#">В работе</a>
                            <a href="#">Сделанные</a>
                        </div>
                    </div>
                    </div>
                    </div>
                    <div class="team__profile root__content">
                        <div class="account__profile__info">
                            <div class="team__logo__block">
                                <div class="team__logo">{{ this_group.logotype }}</div>
                                <p>{{ this_group.description }}</p>
                            </div>
                            <div>
                                <p>{{ this_group.name }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="team__persons__block root__content">
                        <div class="account__content__div">
                            <p class="team__headline">Состав команды</p>
                            <div class="team__persons">
                                {% for object in members %}
                                    <div class="team__person">
                                        <a href="account-smb.html">
                                            <img src="{{ object.avatar }}" alt="avatar">
                                        </a>
                                        <p>{{ object.first_name }}</p>
                                        <p>{{ object.last_name }}</p>
                                        <p>{{ object.profession }}</p>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                    <div class="team__vacancy__block root__content">
                        <div class="drop_block team__headline">
                            Занятые вакансии<i class="fas fa-caret-down drop_caret"></i>
                            <div class="drop_summary team__summary">
                            </div>
                        </div>


                        <div class="drop_block team__headline">
                            Свободные вакансии<i class="fas fa-caret-down drop_caret"></i>
                            <div class="drop_summary team__summary">

                                {% for profession in need_professions %}
                                    <div>
{#                                        <a href="{% url 'groupapp:create_request_in_team' %}">#}
                                            {{ profession }}
                                        </a>
                                    </div>
                                    </div>
                                {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="team__forum root__content">
                    <div class="account__information">
                        <a href="#">
                            <p class="team__headline">Чат/Форум</p>
                        </a>
                    </div>
                </div>
            </div>
    </section>
{% endblock %}

groupapp/templates/groupapp/group_form.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}

{% block conteiner %}
    <div class="registration__form__background">
        <section class="registration__form__content root__container">
            <a href="{% url 'groupapp:groups' %}" class="button__registration__form">
                <img class="button__registration__form__img" src="/static/img/Arrow.png">
                Назад
            </a>
            <h1 class="registration__form__content__h1">
                Заполни форму требованиями к специалистам
            </h1>
            <form action="{% url 'groupapp:update_vacancy'  request.resolver_match.kwargs.pk %}" class="registration__form" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
            {{ vacancyneed.manage_form }}
                {% for form in vacancyneed %}
                    <div>
                        <label for="{{ form.id_for_label }}"
                               class="registration__form_input_label"> {{ form.label }} </label>
                        {{ form }}
                    </div>
                {% endfor %}


                <input type="submit" value="Создать"
                       class="buttons_type_white button__submit__registration__form" id="submit__application">
            </form>
        </section>

    </div>
{% endblock %}

groupapp/templates/groupapp/group_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block conteiner %}
    <div>
    {{ request.resolver_match.kwargs.pk }}
    <a href="{% url 'groupapp:update_vacancy'  request.resolver_match.kwargs.pk %}">редактировать вакансии</a>
    </div>
     <div>
    <a href="{% url 'groupapp:update_group' request.resolver_match.kwargs.pk %}">редактировать данные</a>
    </div>
    <div>
    <a href="{% url 'groupapp:delete_group' request.resolver_match.kwargs.pk %}">удалить команду</a>
    </div>

{% endblock %}

groupapp/templates/groupapp/groups.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}

    <section class="teams root__container">
        <div class="account__background">
            <div class="account__header root__content">
                <p>Команды</p>
                <div class="teams__drop">
                    <div class="drop_block"> Поиск команды<i class="fas fa-caret-down drop_caret"></i>
                        <div class="drop_summary teams__summary">
                            <a href="#">Название</a>
                            <a href="#">Свободные вакансии</a>
                            <a href="#">Дата создания</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="teams__buttons root__content">
                <button class="account__button buttons_type_white">Найти команду</button>
                <button class="account__button buttons_type_white">
                    <a href="{% url 'groupapp:create_group' %}">
                        Создать команду
                    </a>
                </button>
                <a href="{% url 'groupapp:user_groups' %}">
                    <button class="account__button buttons_type_white">Мои команды</button>
                </a>
            </div>
            <div class="teams__block root__content">

                {% for object in object_list %}
                    <div class="teams__part">
                        <a href="{% url "groupapp:group" object.pk %}"><p class="teams__part__logo"></p></a>
                        <p>{{ object.name }}</p>
                        <p>Свободно вакансий &#183; 2</p>
                    </div>
                {% endfor %}

            </div>
            <div class="teams__pages__block root__content">

                <div class="page__active teams__pages">1</div>
                <div class="teams__pages">2</div>
                <div class="teams__pages">3</div>

            </div>
        </div>
    </section>

{% endblock %}